micronaut:
  security:
    enabled: true # <1>
    endpoints:
      login:
        enabled: true # <2>
      oauth:
        enabled: true # <3>
    token:
      jwt:
        enabled: true # <4>
        signatures:
          generator: # <5>
            secret: qrD6h8K6S9503Q06Y6Rfk21TErImPYqa # <7>
